name: vincenthiggins
favicon: null
layout_spectrum: 0.25807493133470416
typography_spectrum: 0.1981468393933028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4518384179100394
  lightness: 0.5134100674185902
  saturation: 0.6761303138919175
  rhythmicContrast: 0.5297333747148514
purpose: []
